mqtt:
  broker_address: mqtt
  broker_port: '1883'
  keep_alive: 15
fleet_info:
  fleetname: kullar
  version: 2.0.0
  versions: v2
  manufacturer: birfen
postgres:
  host: db
  port: '5432'
  database: postgres
  user: postgres
  password: root
maps:
  kullar:
  - map_id: bina_1_floor_0
    map_pgm_path: config/bina_1_floor_0.pgm
    map_yaml_path: config/bina_1_floor_0.yaml
graph:
  C1:
  - - C2
    - 0.1
  - - C9
    - 0.1
  C10:
  - - C11
    - 0.1
  - - C18
    - 0.1
  - - C2
    - 0.1
  - - C9
    - 0.1
  C11:
  - - C10
    - 0.1
  C12:
  - - C13
    - 0.1
  - - C20
    - 0.1
  - - C4
    - 0.1
  C13:
  - - C12
    - 0.1
  - - C14
    - 0.1
  - - C5
    - 0.1
  C14:
  - - C13
    - 0.1
  - - C15
    - 0.1
  - - C22
    - 0.1
  - - C6
    - 0.1
  C15:
  - - C14
    - 0.1
  - - C16
    - 0.1
  - - C7
    - 0.1
  C16:
  - - C15
    - 0.1
  - - C24
    - 0.1
  - - C8
    - 0.1
  C17:
  - - C18
    - 0.1
  - - C25
    - 0.1
  - - C9
    - 0.1
  C18:
  - - C10
    - 0.1
  - - C17
    - 0.1
  - - C19
    - 0.1
  - - C26
    - 0.1
  C19:
  - - C18
    - 0.1
  - - C20
    - 0.1
  - - C27
    - 0.1
  C2:
  - - C1
    - 0.1
  - - C10
    - 0.1
  - - C3
    - 0.1
  C20:
  - - C12
    - 0.1
  - - C19
    - 0.1
  - - C28
    - 0.1
  C21:
  - - C22
    - 0.1
  C22:
  - - C14
    - 0.1
  - - C21
    - 0.1
  - - C23
    - 0.1
  - - C30
    - 0.1
  C23:
  - - C22
    - 0.1
  C24:
  - - C16
    - 0.1
  - - C32
    - 0.1
  - - W24
    - 0.1
  C25:
  - - C17
    - 0.1
  - - C26
    - 0.1
  - - C33
    - 0.1
  C26:
  - - C18
    - 0.1
  - - C25
    - 0.1
  - - C27
    - 0.1
  - - C34
    - 0.1
  C27:
  - - C19
    - 0.1
  - - C26
    - 0.1
  - - C28
    - 0.1
  - - C35
    - 0.1
  C28:
  - - C20
    - 0.1
  - - C27
    - 0.1
  - - C29
    - 0.1
  - - C36
    - 0.1
  C29:
  - - C28
    - 0.1
  - - C30
    - 0.1
  - - C37
    - 0.1
  C3:
  - - C2
    - 0.1
  - - C4
    - 0.1
  C30:
  - - C22
    - 0.1
  - - C29
    - 0.1
  - - C31
    - 0.1
  - - C38
    - 0.1
  C31:
  - - C30
    - 0.1
  - - C32
    - 0.1
  - - C39
    - 0.1
  - - W31
    - 0.1
  C32:
  - - C24
    - 0.1
  - - C31
    - 0.1
  - - C40
    - 0.1
  C33:
  - - C25
    - 0.1
  - - C41
    - 0.1
  C34:
  - - C26
    - 0.1
  C35:
  - - C27
    - 0.1
  - - C36
    - 0.1
  - - C43
    - 0.1
  C36:
  - - C28
    - 0.1
  - - C35
    - 0.1
  - - C37
    - 0.1
  C37:
  - - C29
    - 0.1
  - - C36
    - 0.1
  - - C38
    - 0.1
  - - C45
    - 0.1
  C38:
  - - C30
    - 0.1
  - - C37
    - 0.1
  - - C39
    - 0.1
  - - C46
    - 0.1
  C39:
  - - C31
    - 0.1
  - - C38
    - 0.1
  - - C40
    - 0.1
  - - C47
    - 0.1
  C4:
  - - C12
    - 0.1
  - - C3
    - 0.1
  - - C5
    - 0.1
  C40:
  - - C32
    - 0.1
  - - C39
    - 0.1
  C41:
  - - C33
    - 0.1
  C43:
  - - C35
    - 0.1
  C45:
  - - C37
    - 0.1
  C46:
  - - C38
    - 0.1
  - - C47
    - 0.1
  C47:
  - - C39
    - 0.1
  - - C46
    - 0.1
  - - C48
    - 0.1
  C48:
  - - C47
    - 0.1
  C5:
  - - C13
    - 0.1
  - - C4
    - 0.1
  - - C6
    - 0.1
  - - W5
    - 0.1
  C6:
  - - C14
    - 0.1
  - - C5
    - 0.1
  - - C7
    - 0.1
  C7:
  - - C15
    - 0.1
  - - C6
    - 0.1
  - - C8
    - 0.1
  C8:
  - - C16
    - 0.1
  - - C7
    - 0.1
  C9:
  - - C1
    - 0.1
  - - C10
    - 0.1
  - - C17
    - 0.1
  W24:
  - - C24
    - 0.1
  W31:
  - - C31
    - 0.1
  W5:
  - - C5
    - 0.1
itinerary:
- coordinate:
  - 0.0
  - 0.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C1
- coordinate:
  - 6.0
  - 6.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C10
- coordinate:
  - 12.0
  - 6.0
  - -0.194
  - 0.98
  description: station_dock
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C11
- coordinate:
  - 18.0
  - 6.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C12
- coordinate:
  - 24.0
  - 6.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C13
- coordinate:
  - 30.0
  - 6.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C14
- coordinate:
  - 36.0
  - 6.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C15
- coordinate:
  - 42.0
  - 6.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C16
- coordinate:
  - 0.0
  - 12.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C17
- coordinate:
  - 6.0
  - 12.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C18
- coordinate:
  - 12.0
  - 12.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C19
- coordinate:
  - 6.0
  - 0.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C2
- coordinate:
  - 18.0
  - 12.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C20
- coordinate:
  - 24.0
  - 12.0
  - -0.097
  - 0.995
  description: home_dock
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C21
- coordinate:
  - 30.0
  - 12.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C22
- coordinate:
  - 36.0
  - 12.0
  - -0.097
  - 0.995
  description: station_dock
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C23
- coordinate:
  - 42.0
  - 12.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C24
- coordinate:
  - 0.0
  - 18.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C25
- coordinate:
  - 6.0
  - 18.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C26
- coordinate:
  - 12.0
  - 18.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C27
- coordinate:
  - 18.0
  - 18.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C28
- coordinate:
  - 24.0
  - 18.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C29
- coordinate:
  - 12.0
  - 0.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C3
- coordinate:
  - 30.0
  - 18.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C30
- coordinate:
  - 36.0
  - 18.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C31
- coordinate:
  - 42.0
  - 18.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C32
- coordinate:
  - 0.0
  - 24.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C33
- coordinate:
  - 6.0
  - 24.0
  - -0.097
  - 0.995
  description: station_dock
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C34
- coordinate:
  - 12.0
  - 24.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C35
- coordinate:
  - 18.0
  - 24.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C36
- coordinate:
  - 24.0
  - 24.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C37
- coordinate:
  - 30.0
  - 24.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C38
- coordinate:
  - 36.0
  - 24.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C39
- coordinate:
  - 18.0
  - 0.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C4
- coordinate:
  - 42.0
  - 24.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C40
- coordinate:
  - 0.0
  - 30.0
  - -0.097
  - 0.995
  description: station_dock
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C41
- coordinate:
  - 12.0
  - 30.0
  - -0.194
  - 0.98
  description: charge_dock
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C43
- coordinate:
  - 24.0
  - 30.0
  - -0.097
  - 0.995
  description: home_dock
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C45
- coordinate:
  - 30.0
  - 30.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C46
- coordinate:
  - 36.0
  - 30.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C47
- coordinate:
  - 42.0
  - 30.0
  - -0.194
  - 0.98
  description: station_dock
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C48
- coordinate:
  - 24.0
  - 0.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C5
- coordinate:
  - 30.0
  - 0.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C6
- coordinate:
  - 36.0
  - 0.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C7
- coordinate:
  - 42.0
  - 0.0
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C8
- coordinate:
  - 0.0
  - 6.0
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: C9
- coordinate:
  - 43.44
  - 13.928
  - -0.194
  - 0.98
  description: waitpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: W24
- coordinate:
  - 36.969
  - 19.69
  - -0.097
  - 0.995
  description: waitpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: W31
- coordinate:
  - 25.424
  - 1.35
  - -0.194
  - 0.98
  description: waitpoint
  fleet_id: kullar
  map_id: bina_1_floor_0
  loc_id: W5
