- fleetname: kullar
  robot_serial_number: R01
  versions: v2
  version: 2.0.0
  manufacturer: birfen
  connection_state: ONLINE
  initial_position:
  - 24.0
  - 30.0
  - 0.0
  bat_charge: 59.7
  lin_velocity: 0.65
  ang_velocity: 0.15
- fleetname: kullar
  robot_serial_number: R02
  versions: v2
  version: 2.0.0
  manufacturer: birfen
  connection_state: ONLINE
  initial_position:
  - 24.0
  - 12.0
  - 0.0
  bat_charge: 76.3
  lin_velocity: 0.65
  ang_velocity: 0.15
